/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pethotelapp.Application;

import javax.swing.table.*;
import javax.swing.*;
import java.awt.*;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import com.mycompany.pethotelapp.Projects.Customer;

import com.mycompany.pethotelapp.Functions.home;
import com.mycompany.pethotelapp.Functions.Customerapp;
import com.mycompany.pethotelapp.Functions.Staff;
import com.mycompany.pethotelapp.Functions.Petapp;
import com.mycompany.pethotelapp.Functions.Storage;


/**
 *
 * @author Eternal
 */

public class main extends javax.swing.JFrame {
    private Date checkin;
    private Date checkout;
    private double amount;

    /**
     * Creates new form Sample2
     */
    public void showcustable(){
        String[] tablecustomer = {"ID Customer", "Name Customer", "Phone Number", "Address", "Check In", "Check Out"};
        DefaultTableModel model = new DefaultTableModel(null,tablecustomer);
        Customerapp customerapp = new Customerapp();
        customerapp.selectCustomer(model);
        cusTable.setModel(model); 
    }
    public void showpettable(){
        String[] tablepet ={
            "ID Pet", "Name Pet", "ID Customer", "Name Customer", "Room Number", "ID Service"
        };
        DefaultTableModel model = new DefaultTableModel(null,tablepet);
        Petapp petapp = new Petapp();
        petapp.selecePet(model);
        pet2Table.setModel(model);
    }
    public void showstafftable(){
        String[] staffColumns = {"ID Staff", "Name Staff", "Phone Number", "Address", "Date Of Birth", "Email", "Start Date"};
        DefaultTableModel model = new DefaultTableModel(null, staffColumns);
        Staff staffApp = new Staff();
        staffApp.selectAllStaff(model); 
        staTable.setModel(model); 
    }
    public void showstoragetable(){
        String[] tablestorage = {
            "ID Product", "Name Product", "Status", "Date of entry"
        };
        DefaultTableModel model = new DefaultTableModel(null, tablestorage);
        Storage storage = new Storage();
        storage.selectAllStorage(model);
        stoTable.setModel(model);
    }
    public main() {
        initComponents();
        setLocationRelativeTo(null);
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String dateString = formatter.format(date);
        this.checkin=date;
        jtcheckin.setText(dateString);
               
    }
    public void checkOut(){
        String dateString=jtcheckout.getText();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        try{
            Date date = formatter.parse(dateString);
            this.checkout = date;
        }catch(ParseException e){
            e.printStackTrace();
        }
    }
    
    int width = 170;
    int height = 750;
    
    void closeMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i=width; i>0; i--) {
                    slideMenu.setSize(i, height);
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        //Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
    
    void openMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i=0; i<width; i++) {
                    slideMenu.setSize(i, height);
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        //Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        controlBar = new javax.swing.JPanel();
        homeButton = new javax.swing.JLabel();
        slideMenu = new javax.swing.JPanel();
        slideOff = new javax.swing.JLabel();
        petHotelTitle = new javax.swing.JLabel();
        petHotelLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        home = new javax.swing.JLabel();
        customers = new javax.swing.JLabel();
        staffs = new javax.swing.JLabel();
        pets = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        logOut = new javax.swing.JLabel();
        storage = new javax.swing.JLabel();
        slideOn = new javax.swing.JLabel();
        mainBoard = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        homeInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        customerInfoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idCustomer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameCustomer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneNumberCustomer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addressCustomer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addCusBtn = new javax.swing.JLabel();
        saveCusBtn = new javax.swing.JLabel();
        resetCusBtn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtcheckin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtcheckout = new javax.swing.JTextField();
        billPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtidcustomersearch = new javax.swing.JTextField();
        searchBillBtn = new javax.swing.JLabel();
        payBillBtn = new javax.swing.JLabel();
        resetBillBtn = new javax.swing.JLabel();
        tnamecustomer = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        jtamount = new javax.swing.JLabel();
        StatisticsPanel = new javax.swing.JPanel();
        customerInfo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        customerInfoLabel = new javax.swing.JLabel();
        searchCusBtn = new javax.swing.JLabel();
        jtsearch = new javax.swing.JTextField();
        deleteCusBtn = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cusTable = new javax.swing.JTable();
        petInfo = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        petInfoLabel = new javax.swing.JLabel();
        petTable = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        pet2Table = new javax.swing.JTable();
        searchPetBtn = new javax.swing.JLabel();
        jtsearchpet = new javax.swing.JTextField();
        deletePetBtn = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        staffInfo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        staffInfoLabel = new javax.swing.JLabel();
        staffTable = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        staTable = new javax.swing.JTable();
        searchStaffBtn = new javax.swing.JLabel();
        jtsearchstaff = new javax.swing.JTextField();
        addStaffBtn = new javax.swing.JLabel();
        deleteStaffBtn = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        storageInfo = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        storageLabel = new javax.swing.JLabel();
        jtsearchproduct = new javax.swing.JTextField();
        searchStorageBtn = new javax.swing.JLabel();
        addStorageBtn = new javax.swing.JLabel();
        deleteStorageBtn = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        stoTable = new javax.swing.JTable();

        jLabel12.setText("jLabel12");

        jLabel13.setText("Search");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        controlBar.setBackground(new java.awt.Color(255, 192, 77));
        controlBar.setMaximumSize(new java.awt.Dimension(950, 750));
        controlBar.setMinimumSize(new java.awt.Dimension(950, 750));
        controlBar.setPreferredSize(new java.awt.Dimension(950, 750));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home.png"))); // NOI18N
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });

        slideMenu.setBackground(new java.awt.Color(255, 192, 77));
        slideMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        slideMenu.setMaximumSize(new java.awt.Dimension(170, 750));
        slideMenu.setMinimumSize(new java.awt.Dimension(170, 750));
        slideMenu.setPreferredSize(new java.awt.Dimension(170, 750));
        slideMenu.setRequestFocusEnabled(false);
        slideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slideOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CloseMenu.png"))); // NOI18N
        slideOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slideOffMouseClicked(evt);
            }
        });
        slideMenu.add(slideOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 30, 30));

        petHotelTitle.setBackground(new java.awt.Color(255, 255, 255));
        petHotelTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        petHotelTitle.setForeground(new java.awt.Color(75, 75, 75));
        petHotelTitle.setText("Pet Hotel");
        slideMenu.add(petHotelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        petHotelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo1Upd.png"))); // NOI18N
        slideMenu.add(petHotelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 153, 0));
        slideMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 236, 165, -1));

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        home.setForeground(new java.awt.Color(51, 51, 51));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("Home");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        slideMenu.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 40));

        customers.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        customers.setForeground(new java.awt.Color(51, 51, 51));
        customers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customers.setText("Customers");
        customers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        customers.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersMouseClicked(evt);
            }
        });
        slideMenu.add(customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 170, 40));

        staffs.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        staffs.setForeground(new java.awt.Color(51, 51, 51));
        staffs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staffs.setText("Staffs");
        staffs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        staffs.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        staffs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffsMouseClicked(evt);
            }
        });
        slideMenu.add(staffs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 170, 40));

        pets.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pets.setForeground(new java.awt.Color(51, 51, 51));
        pets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pets.setText("Pets");
        pets.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pets.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petsMouseClicked(evt);
            }
        });
        slideMenu.add(pets, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 170, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 153, 0));
        slideMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 549, 165, 10));

        logOut.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        logOut.setForeground(new java.awt.Color(51, 51, 51));
        logOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOut.setText("Log out");
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
        });
        slideMenu.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 170, 40));

        storage.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        storage.setForeground(new java.awt.Color(51, 51, 51));
        storage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storage.setText("Storage");
        storage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        storage.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        storage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storageMouseClicked(evt);
            }
        });
        slideMenu.add(storage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 170, 40));

        slideOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpenMenu.png"))); // NOI18N
        slideOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slideOnMouseClicked(evt);
            }
        });

        mainBoard.setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(245, 245, 245));
        mainPanel.setMaximumSize(new java.awt.Dimension(950, 750));
        mainPanel.setPreferredSize(new java.awt.Dimension(950, 750));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.png"))); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainBoard.add(mainPanel, "card6");

        homeInfo.setBackground(new java.awt.Color(255, 255, 255));
        homeInfo.setMaximumSize(new java.awt.Dimension(950, 750));
        homeInfo.setMinimumSize(new java.awt.Dimension(950, 750));
        homeInfo.setPreferredSize(new java.awt.Dimension(950, 750));

        jPanel1.setBackground(new java.awt.Color(255, 255, 225));

        customerInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        customerInfoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        customerInfoPanel.setMaximumSize(new java.awt.Dimension(32767, 259));

        jLabel2.setText("ID Customer ");

        idCustomer.setEditable(false);
        idCustomer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Name");

        jLabel4.setText("Phone number");

        jLabel5.setText("Address");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Customer Information");

        addCusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addpet.png"))); // NOI18N
        addCusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCusBtnMouseClicked(evt);
            }
        });

        saveCusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save.png"))); // NOI18N
        saveCusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveCusBtnMouseClicked(evt);
            }
        });

        resetCusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        resetCusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetCusBtnMouseClicked(evt);
            }
        });

        jLabel8.setText("Check in");

        jLabel9.setText("Check out");

        javax.swing.GroupLayout customerInfoPanelLayout = new javax.swing.GroupLayout(customerInfoPanel);
        customerInfoPanel.setLayout(customerInfoPanelLayout);
        customerInfoPanelLayout.setHorizontalGroup(
            customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerInfoPanelLayout.createSequentialGroup()
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customerInfoPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetCusBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCusBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveCusBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, customerInfoPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idCustomer)
                            .addComponent(nameCustomer)
                            .addComponent(phoneNumberCustomer)
                            .addComponent(addressCustomer)
                            .addComponent(jtcheckin)
                            .addComponent(jtcheckout))))
                .addGap(26, 26, 26))
            .addGroup(customerInfoPanelLayout.createSequentialGroup()
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(customerInfoPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(customerInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        customerInfoPanelLayout.setVerticalGroup(
            customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(idCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(phoneNumberCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addressCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtcheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtcheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCusBtn)
                    .addComponent(saveCusBtn)
                    .addComponent(resetCusBtn))
                .addGap(14, 14, 14))
        );

        billPanel.setBackground(new java.awt.Color(255, 255, 255));
        billPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        billPanel.setMaximumSize(new java.awt.Dimension(32767, 259));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setText("Bill");

        jLabel11.setText("ID Customer");

        searchBillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        searchBillBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBillBtnMouseClicked(evt);
            }
        });

        payBillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pay.png"))); // NOI18N
        payBillBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payBillBtnMouseClicked(evt);
            }
        });

        resetBillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        resetBillBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetBillBtnMouseClicked(evt);
            }
        });

        tnamecustomer.setText("Name Customer: ");

        billTable.setBackground(new java.awt.Color(255, 204, 102));
        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Pet", "Name Pet", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        billTable.setGridColor(new java.awt.Color(255, 204, 51));
        billTable.setRowHeight(30);
        billTable.setSelectionBackground(new java.awt.Color(255, 204, 102));
        jScrollPane6.setViewportView(billTable);

        jtamount.setText("Total amount:");

        javax.swing.GroupLayout billPanelLayout = new javax.swing.GroupLayout(billPanel);
        billPanel.setLayout(billPanelLayout);
        billPanelLayout.setHorizontalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billPanelLayout.createSequentialGroup()
                        .addComponent(resetBillBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(payBillBtn)
                        .addGap(16, 16, 16))))
            .addGroup(billPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(billPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtidcustomersearch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchBillBtn))
                            .addComponent(tnamecustomer))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtamount)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        billPanelLayout.setVerticalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBillBtn)
                    .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jtidcustomersearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tnamecustomer)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtamount)
                .addGap(15, 15, 15)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(payBillBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resetBillBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout StatisticsPanelLayout = new javax.swing.GroupLayout(StatisticsPanel);
        StatisticsPanel.setLayout(StatisticsPanelLayout);
        StatisticsPanelLayout.setHorizontalGroup(
            StatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        StatisticsPanelLayout.setVerticalGroup(
            StatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(customerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(billPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(billPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homeInfoLayout = new javax.swing.GroupLayout(homeInfo);
        homeInfo.setLayout(homeInfoLayout);
        homeInfoLayout.setHorizontalGroup(
            homeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeInfoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        homeInfoLayout.setVerticalGroup(
            homeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeInfoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainBoard.add(homeInfo, "card3");

        customerInfo.setBackground(new java.awt.Color(255, 255, 255));
        customerInfo.setMaximumSize(new java.awt.Dimension(950, 750));
        customerInfo.setPreferredSize(new java.awt.Dimension(950, 750));

        jPanel3.setBackground(new java.awt.Color(255, 255, 225));
        jPanel3.setPreferredSize(new java.awt.Dimension(870, 700));

        customerInfoLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        customerInfoLabel.setText("Customer Information");
        customerInfoLabel.setMaximumSize(new java.awt.Dimension(260, 30));
        customerInfoLabel.setMinimumSize(new java.awt.Dimension(260, 30));
        customerInfoLabel.setPreferredSize(new java.awt.Dimension(260, 30));

        searchCusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        searchCusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchCusBtnMouseClicked(evt);
            }
        });

        jtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtsearchActionPerformed(evt);
            }
        });

        deleteCusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete.png"))); // NOI18N
        deleteCusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCusBtnMouseClicked(evt);
            }
        });

        jLabel14.setText("ID Customer");

        cusTable.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cusTable.setRowHeight(30);
        JTableHeader cusHeader = cusTable.getTableHeader();
        cusHeader.setDefaultRenderer(new headerRenderer());
        jScrollPane2.setViewportView(cusTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(customerInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchCusBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteCusBtn)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(customerInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteCusBtn)
                    .addComponent(searchCusBtn)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout customerInfoLayout = new javax.swing.GroupLayout(customerInfo);
        customerInfo.setLayout(customerInfoLayout);
        customerInfoLayout.setHorizontalGroup(
            customerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerInfoLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        customerInfoLayout.setVerticalGroup(
            customerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        mainBoard.add(customerInfo, "card2");

        petInfo.setBackground(new java.awt.Color(255, 255, 255));
        petInfo.setMaximumSize(new java.awt.Dimension(950, 750));
        petInfo.setMinimumSize(new java.awt.Dimension(950, 750));

        jPanel5.setBackground(new java.awt.Color(255, 255, 225));
        jPanel5.setPreferredSize(new java.awt.Dimension(870, 700));

        petInfoLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        petInfoLabel.setText("Pet Information");
        petInfoLabel.setMaximumSize(new java.awt.Dimension(260, 30));
        petInfoLabel.setMinimumSize(new java.awt.Dimension(260, 30));
        petInfoLabel.setPreferredSize(new java.awt.Dimension(260, 30));

        pet2Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pet", "Name Pet", "ID Customer", "Name Customer", "Room", "ID Service"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pet2Table.setRowHeight(30);
        JTableHeader petHeader = pet2Table.getTableHeader();
        petHeader.setDefaultRenderer(new headerRenderer());
        jScrollPane4.setViewportView(pet2Table);
        if (pet2Table.getColumnModel().getColumnCount() > 0) {
            pet2Table.getColumnModel().getColumn(0).setResizable(false);
            pet2Table.getColumnModel().getColumn(1).setResizable(false);
            pet2Table.getColumnModel().getColumn(2).setResizable(false);
            pet2Table.getColumnModel().getColumn(3).setResizable(false);
            pet2Table.getColumnModel().getColumn(4).setResizable(false);
            pet2Table.getColumnModel().getColumn(5).setResizable(false);
        }

        petTable.setViewportView(jScrollPane4);

        searchPetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        searchPetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchPetBtnMouseClicked(evt);
            }
        });

        deletePetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete.png"))); // NOI18N
        deletePetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletePetBtnMouseClicked(evt);
            }
        });

        jLabel15.setText("ID Pet:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(petInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtsearchpet, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchPetBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletePetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(petTable, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(petInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPetBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtsearchpet, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(deletePetBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(petTable, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout petInfoLayout = new javax.swing.GroupLayout(petInfo);
        petInfo.setLayout(petInfoLayout);
        petInfoLayout.setHorizontalGroup(
            petInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, petInfoLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        petInfoLayout.setVerticalGroup(
            petInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petInfoLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        mainBoard.add(petInfo, "card5");

        staffInfo.setBackground(new java.awt.Color(255, 255, 255));
        staffInfo.setMaximumSize(new java.awt.Dimension(950, 750));
        staffInfo.setPreferredSize(new java.awt.Dimension(950, 750));

        jPanel4.setBackground(new java.awt.Color(255, 255, 225));
        jPanel4.setPreferredSize(new java.awt.Dimension(870, 700));

        staffInfoLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        staffInfoLabel.setText("Staff Information");
        staffInfoLabel.setMaximumSize(new java.awt.Dimension(260, 30));
        staffInfoLabel.setMinimumSize(new java.awt.Dimension(260, 30));
        staffInfoLabel.setPreferredSize(new java.awt.Dimension(260, 30));

        staTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Staff", "Name Staff", "Phone Number", "Address", "Date Of Birth", "Email", "Start Date"
            }
        ));
        staTable.setGridColor(new java.awt.Color(0, 0, 0));
        staTable.setRowHeight(30);
        staTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        staTable.setBackground(Color.WHITE);
        JTableHeader staHeader = staTable.getTableHeader();
        staHeader.setDefaultRenderer(new headerRenderer());
        jScrollPane3.setViewportView(staTable);
        if (staTable.getColumnModel().getColumnCount() > 0) {
            staTable.getColumnModel().getColumn(0).setResizable(false);
            staTable.getColumnModel().getColumn(1).setResizable(false);
            staTable.getColumnModel().getColumn(2).setResizable(false);
            staTable.getColumnModel().getColumn(3).setResizable(false);
            staTable.getColumnModel().getColumn(4).setResizable(false);
            staTable.getColumnModel().getColumn(5).setResizable(false);
            staTable.getColumnModel().getColumn(6).setResizable(false);
        }

        staffTable.setViewportView(jScrollPane3);

        searchStaffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        searchStaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchStaffBtnMouseClicked(evt);
            }
        });

        jtsearchstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtsearchstaffActionPerformed(evt);
            }
        });

        addStaffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        addStaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStaffBtnMouseClicked(evt);
            }
        });

        deleteStaffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete.png"))); // NOI18N
        deleteStaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteStaffBtnMouseClicked(evt);
            }
        });

        jLabel16.setText("ID Staff:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffTable, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtsearchstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchStaffBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addStaffBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteStaffBtn)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(staffInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(staffInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteStaffBtn)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addStaffBtn)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtsearchstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))))
                        .addGap(12, 12, 12)
                        .addComponent(staffTable, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchStaffBtn))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout staffInfoLayout = new javax.swing.GroupLayout(staffInfo);
        staffInfo.setLayout(staffInfoLayout);
        staffInfoLayout.setHorizontalGroup(
            staffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffInfoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        staffInfoLayout.setVerticalGroup(
            staffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffInfoLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        mainBoard.add(staffInfo, "card4");
        staffInfo.getAccessibleContext().setAccessibleDescription("");

        storageInfo.setBackground(new java.awt.Color(255, 255, 255));
        storageInfo.setMaximumSize(new java.awt.Dimension(950, 750));
        storageInfo.setMinimumSize(new java.awt.Dimension(950, 750));
        storageInfo.setPreferredSize(new java.awt.Dimension(950, 750));

        jPanel12.setBackground(new java.awt.Color(255, 255, 225));
        jPanel12.setPreferredSize(new java.awt.Dimension(850, 730));

        storageLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        storageLabel.setText("Storage");
        storageLabel.setMaximumSize(new java.awt.Dimension(260, 30));
        storageLabel.setMinimumSize(new java.awt.Dimension(260, 30));
        storageLabel.setPreferredSize(new java.awt.Dimension(260, 30));

        searchStorageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        searchStorageBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchStorageBtnMouseClicked(evt);
            }
        });

        addStorageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        addStorageBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStorageBtnMouseClicked(evt);
            }
        });

        deleteStorageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete.png"))); // NOI18N
        deleteStorageBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteStorageBtnMouseClicked(evt);
            }
        });

        jLabel17.setText("ID Product:");

        stoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Porduct", "Name Product", "Status", "Date of entry"
            }
        ));
        stoTable.setRowHeight(30);
        JTableHeader stoHeader = stoTable.getTableHeader();
        stoHeader.setDefaultRenderer(new headerRenderer());
        jScrollPane7.setViewportView(stoTable);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(storageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtsearchproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchStorageBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addStorageBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteStorageBtn))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(storageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteStorageBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addStorageBtn))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtsearchproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addComponent(searchStorageBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout storageInfoLayout = new javax.swing.GroupLayout(storageInfo);
        storageInfo.setLayout(storageInfoLayout);
        storageInfoLayout.setHorizontalGroup(
            storageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storageInfoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        storageInfoLayout.setVerticalGroup(
            storageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storageInfoLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        mainBoard.add(storageInfo, "card5");

        javax.swing.GroupLayout controlBarLayout = new javax.swing.GroupLayout(controlBar);
        controlBar.setLayout(controlBarLayout);
        controlBarLayout.setHorizontalGroup(
            controlBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlBarLayout.createSequentialGroup()
                .addComponent(slideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(controlBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlBarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(slideOn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeButton)
                        .addGap(47, 47, 47))))
        );
        controlBarLayout.setVerticalGroup(
            controlBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlBarLayout.createSequentialGroup()
                .addGroup(controlBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlBarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(controlBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(slideOn)
                            .addComponent(homeButton))
                        .addGap(18, 18, 18)
                        .addComponent(mainBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(slideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slideOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideOffMouseClicked
        closeMenu();
    }//GEN-LAST:event_slideOffMouseClicked

    private void slideOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideOnMouseClicked
        openMenu();
    }//GEN-LAST:event_slideOnMouseClicked

    private void customersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersMouseClicked
        mainPanel.setVisible(false);
        customerInfo.setVisible(true);
        homeInfo.setVisible(false);
        staffInfo.setVisible(false);
        petInfo.setVisible(false);
        storageInfo.setVisible(false);
        showcustable();
    }//GEN-LAST:event_customersMouseClicked

    private void staffsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffsMouseClicked
        mainPanel.setVisible(false);
        customerInfo.setVisible(false);
        staffInfo.setVisible(true);
        homeInfo.setVisible(false);
        petInfo.setVisible(false);
        storageInfo.setVisible(false);
        showstafftable();
    }//GEN-LAST:event_staffsMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        mainPanel.setVisible(false);
        customerInfo.setVisible(false);
        staffInfo.setVisible(false);
        homeInfo.setVisible(true);
        petInfo.setVisible(false);
        storageInfo.setVisible(false);
        
    }//GEN-LAST:event_homeMouseClicked

    private void petsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petsMouseClicked
        mainPanel.setVisible(false);
        petInfo.setVisible(true);
        customerInfo.setVisible(false);
        staffInfo.setVisible(false);
        homeInfo.setVisible(false);
        storageInfo.setVisible(false);
        showpettable();
    }//GEN-LAST:event_petsMouseClicked

    private void storageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storageMouseClicked
        storageInfo.setVisible(true);
        mainPanel.setVisible(false);
        customerInfo.setVisible(false);
        staffInfo.setVisible(false);
        homeInfo.setVisible(false);
        petInfo.setVisible(false);
        showstoragetable();
    }//GEN-LAST:event_storageMouseClicked

    private void addCusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCusBtnMouseClicked
        addPetFrame petFrame = new addPetFrame(); 
        petFrame.setID_customer(Integer.parseInt(idCustomer.getText()));
        petFrame.setVisible(true);
        petFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_addCusBtnMouseClicked

    private void saveCusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveCusBtnMouseClicked
        checkOut();
        Customer customer = new Customer(0, nameCustomer.getText(),phoneNumberCustomer.getText(), addressCustomer.getText(),checkin,checkout);
        home dbConnection = new home();
        int id_customer = dbConnection.addCustomer(customer);
        idCustomer.setText(String.valueOf(id_customer));
        JOptionPane.showMessageDialog(this, "Successfully added customer " + nameCustomer.getText() + " !");
      
    }//GEN-LAST:event_saveCusBtnMouseClicked

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        storageInfo.setVisible(false);
        mainPanel.setVisible(true);
        customerInfo.setVisible(false);
        staffInfo.setVisible(false);
        homeInfo.setVisible(false);
        petInfo.setVisible(false);
    }//GEN-LAST:event_homeButtonMouseClicked

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_logOutMouseClicked

    private void addStaffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStaffBtnMouseClicked
        addStaffFrame staffFrame = new addStaffFrame();
        staffFrame.setVisible(true);
        staffFrame.setLocationRelativeTo(null);
        showstafftable();
    }//GEN-LAST:event_addStaffBtnMouseClicked

    private void resetCusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetCusBtnMouseClicked
        idCustomer.setText("");
        nameCustomer.setText("");
        addressCustomer.setText("");
        phoneNumberCustomer.setText("");
        jtcheckout.setText("");
    }//GEN-LAST:event_resetCusBtnMouseClicked

    private void searchCusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchCusBtnMouseClicked
        String search=jtsearch.getText();
        if(jtsearch.getText().equals("")){
            showcustable();
        }
            String[] tablecustomer = {"ID Customer", "Name Customer", "Phone Number", "Address", "Check In", "Check Out"};
            DefaultTableModel model = new DefaultTableModel(null,tablecustomer);
            Customerapp customerapp = new Customerapp();
            customerapp.selectOneCustomer(model, search);
            cusTable.setModel(model); 
       
    }//GEN-LAST:event_searchCusBtnMouseClicked

    private void deleteCusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCusBtnMouseClicked
  
        Customerapp customerapp = new Customerapp();
        int selectedRow = cusTable.getSelectedRow();
        Object value = cusTable.getValueAt(selectedRow, 0);
        customerapp.deleteCustomer(value.toString());
        showcustable();
        JOptionPane.showMessageDialog(this, "Successfully delete customer !");
    }//GEN-LAST:event_deleteCusBtnMouseClicked

    private void jtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtsearchActionPerformed
       
    }//GEN-LAST:event_jtsearchActionPerformed

    private void searchBillBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBillBtnMouseClicked
        String[] tablebill = {"ID Pet", "Name Pet","Price"};
        double amount1 = 0;
        DefaultTableModel model = new DefaultTableModel(null,tablebill);
        home home = new home();
        String nameCustomer = home.selectCustomer(model, jtidcustomersearch.getText());
        tnamecustomer.setText("Name Customer: "+ nameCustomer);
        billTable.setModel(model);
        for(int i = 0;i<billTable.getRowCount();i++){
            Object value = billTable.getValueAt(i, 2);
            if(value instanceof Number){
                amount1 += ((Number) value).doubleValue();
            }
        }
        this.amount=amount1;
        jtamount.setText("Total amount: "+String.valueOf(amount));
        
    }//GEN-LAST:event_searchBillBtnMouseClicked

    private void resetBillBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBillBtnMouseClicked
        jtidcustomersearch.setText("");
        tnamecustomer.setText("Name Customer: ");
        String[] tablebill = {"ID Pet", "Name Pet","Price"};
        DefaultTableModel model = new DefaultTableModel(null,tablebill);
        billTable.setModel(model);
        jtamount.setText("Total amount: ");
    }//GEN-LAST:event_resetBillBtnMouseClicked

    private void deleteStaffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteStaffBtnMouseClicked
        Staff staff = new Staff();
        int selectedRow = staTable.getSelectedRow();
        Object value = staTable.getValueAt(selectedRow, 0);
        staff.deleteStaff(Integer.parseInt(value.toString()));
        showstafftable();
        JOptionPane.showMessageDialog(this, "Successfully delete staff !");
    }//GEN-LAST:event_deleteStaffBtnMouseClicked

    private void deletePetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePetBtnMouseClicked
        Petapp petapp = new Petapp();
        int selectedRow = pet2Table.getSelectedRow();
        Object value = pet2Table.getValueAt(selectedRow, 0);
        petapp.removePet(Integer.parseInt(value.toString()));
        showpettable();
        JOptionPane.showMessageDialog(this, "Successfully delete pet !");
    }//GEN-LAST:event_deletePetBtnMouseClicked

    private void searchPetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPetBtnMouseClicked
        if(jtsearchpet.getText().equals("")){
            showpettable();
        }else{
            String[] tablepet ={
                "ID Pet", "Name Pet", "ID Customer", "Name Customer", "Room Number", "ID Service"
            };
            DefaultTableModel model = new DefaultTableModel(null,tablepet);
            Petapp petapp = new Petapp();
            petapp.seleceOnePet(model,Integer.parseInt(jtsearchpet.getText()));
            pet2Table.setModel(model);
        }
    }//GEN-LAST:event_searchPetBtnMouseClicked

    private void addStorageBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStorageBtnMouseClicked
        addStorage addstorage = new addStorage();
        addstorage.setVisible(true);
        addstorage.setLocationRelativeTo(null);
        showstoragetable();
    }//GEN-LAST:event_addStorageBtnMouseClicked

    private void searchStaffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStaffBtnMouseClicked
        if(jtsearchstaff.getText().equals("")){
            showstafftable();
        }else{
            String[] tablestaff = {"ID Staff", "Name Staff", "Phone Number", "Address", "Date Of Birth", "Email", "Start Date"};
            DefaultTableModel model = new DefaultTableModel(null,tablestaff);
            Staff staff = new Staff();
            staff.searchStaff(model,jtsearchstaff.getText());
            staTable.setModel(model);
        }
    }//GEN-LAST:event_searchStaffBtnMouseClicked

    private void jtsearchstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtsearchstaffActionPerformed
        String[] tablestaff = {"ID Staff", "Name Staff", "Phone Number", "Address", "Date Of Birth", "Email", "Start Date"};
        DefaultTableModel model = new DefaultTableModel(null,tablestaff);
        Staff staff = new Staff();
        staff.searchStaff(model,jtsearchstaff.getText());
        staTable.setModel(model);
    }//GEN-LAST:event_jtsearchstaffActionPerformed

    private void deleteStorageBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteStorageBtnMouseClicked
        Storage storage = new Storage();
        int selectedRow = stoTable.getSelectedRow();
        Object value = stoTable.getValueAt(selectedRow, 0);
        storage.removeStorage(Integer.parseInt(value.toString()));
        showstoragetable();
        JOptionPane.showMessageDialog(this, "Successfully delete product !");
    }//GEN-LAST:event_deleteStorageBtnMouseClicked

    private void searchStorageBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStorageBtnMouseClicked
        if(jtsearchproduct.getText().equals("")){
            showstoragetable();
            }else{
            String[] tablestorage = {
                "ID Product", "Name Product", "Status", "Date of entry"
            };
            DefaultTableModel model = new DefaultTableModel(null, tablestorage);
            Storage storage = new Storage();
            storage.selectOneProduct(model, Integer.parseInt(jtsearchproduct.getText()));
            stoTable.setModel(model);
        }
    }//GEN-LAST:event_searchStorageBtnMouseClicked

    private void payBillBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payBillBtnMouseClicked
        payCard paycard = new payCard();
        paycard.setAmount(amount);
        paycard.setID_Customer(jtidcustomersearch.getText());
        paycard.setVisible(true);
        paycard.setLocationRelativeTo(null);
        jtidcustomersearch.setText("");
        tnamecustomer.setText("Name Customer: ");
        String[] tablebill = {"ID Pet", "Name Pet","Price"};
        DefaultTableModel model = new DefaultTableModel(null,tablebill);
        billTable.setModel(model);
        jtamount.setText("Total amount: ");
    }//GEN-LAST:event_payBillBtnMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new main();
        
        /* Set the Windows look and feel */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StatisticsPanel;
    private javax.swing.JLabel addCusBtn;
    private javax.swing.JLabel addStaffBtn;
    private javax.swing.JLabel addStorageBtn;
    private javax.swing.JTextField addressCustomer;
    private javax.swing.JPanel billPanel;
    private javax.swing.JTable billTable;
    private javax.swing.JPanel controlBar;
    private javax.swing.JTable cusTable;
    private javax.swing.JPanel customerInfo;
    private javax.swing.JLabel customerInfoLabel;
    private javax.swing.JPanel customerInfoPanel;
    private javax.swing.JLabel customers;
    private javax.swing.JLabel deleteCusBtn;
    private javax.swing.JLabel deletePetBtn;
    private javax.swing.JLabel deleteStaffBtn;
    private javax.swing.JLabel deleteStorageBtn;
    private javax.swing.JLabel home;
    private javax.swing.JLabel homeButton;
    private javax.swing.JPanel homeInfo;
    private javax.swing.JTextField idCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel jtamount;
    private javax.swing.JTextField jtcheckin;
    private javax.swing.JTextField jtcheckout;
    private javax.swing.JTextField jtidcustomersearch;
    private javax.swing.JTextField jtsearch;
    private javax.swing.JTextField jtsearchpet;
    private javax.swing.JTextField jtsearchproduct;
    private javax.swing.JTextField jtsearchstaff;
    private javax.swing.JLabel logOut;
    private javax.swing.JPanel mainBoard;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameCustomer;
    private javax.swing.JLabel payBillBtn;
    private javax.swing.JTable pet2Table;
    private javax.swing.JLabel petHotelLogo;
    private javax.swing.JLabel petHotelTitle;
    private javax.swing.JPanel petInfo;
    private javax.swing.JLabel petInfoLabel;
    private javax.swing.JScrollPane petTable;
    private javax.swing.JLabel pets;
    private javax.swing.JTextField phoneNumberCustomer;
    private javax.swing.JLabel resetBillBtn;
    private javax.swing.JLabel resetCusBtn;
    private javax.swing.JLabel saveCusBtn;
    private javax.swing.JLabel searchBillBtn;
    private javax.swing.JLabel searchCusBtn;
    private javax.swing.JLabel searchPetBtn;
    private javax.swing.JLabel searchStaffBtn;
    private javax.swing.JLabel searchStorageBtn;
    private javax.swing.JPanel slideMenu;
    private javax.swing.JLabel slideOff;
    private javax.swing.JLabel slideOn;
    private javax.swing.JTable staTable;
    private javax.swing.JPanel staffInfo;
    private javax.swing.JLabel staffInfoLabel;
    private javax.swing.JScrollPane staffTable;
    private javax.swing.JLabel staffs;
    private javax.swing.JTable stoTable;
    private javax.swing.JLabel storage;
    private javax.swing.JPanel storageInfo;
    private javax.swing.JLabel storageLabel;
    private javax.swing.JLabel tnamecustomer;
    // End of variables declaration//GEN-END:variables
}
