/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pethotelapp.Application;

/**
 *
 * @author Asus
 */

import java.awt.*;
import javax.swing.*;
import com.mycompany.stripeswing.StripePaymentLogic;
import com.mycompany.pethotelapp.Projects.Bill;
import com.mycompany.pethotelapp.Functions.Payment;
import com.mycompany.pethotelapp.Functions.Customerapp;

public class payCard extends javax.swing.JFrame {
    private String id_customer;
    private double amount;
    /**
     * Creates new form paymentCard
     */
    public payCard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(addStaffFrame.DISPOSE_ON_CLOSE);
    }
    public void setID_Customer(String id_customer){
        this.id_customer=id_customer;
    }
    public void setAmount(double amount){
        this.amount=amount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cardEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cardNumber = new javax.swing.JTextField();
        cardCVC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cardName = new javax.swing.JTextField();
        countryList = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cardExpDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logincat1.PNG"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logincat2.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setName(""); // NOI18N
        jPanel1.setRequestFocusEnabled(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Email");

        cardEmail.setForeground(new java.awt.Color(204, 204, 204));
        cardEmail.setText("Ex: pethotel@abc.com");
        cardEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardEmailFocusLost(evt);
            }
        });
        cardEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardEmailActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Card Number");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pay.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        cardNumber.setForeground(new java.awt.Color(204, 204, 204));
        cardNumber.setText("1234 1234 1234 1234");
        cardNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardNumberFocusLost(evt);
            }
        });
        cardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberActionPerformed(evt);
            }
        });

        cardCVC.setForeground(new java.awt.Color(204, 204, 204));
        cardCVC.setText("CVC");
        cardCVC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardCVCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardCVCFocusLost(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Cardholder Name");

        cardName.setForeground(new java.awt.Color(204, 204, 204));
        cardName.setText("Ex: NGUYEN VAN AN");
        cardName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardNameFocusLost(evt);
            }
        });

        countryList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vietnam", "Korea", "China", "US America", "Spain", "Japan" }));
        countryList.setBackground(Color.WHITE);
        countryList.setForeground(Color.decode("#666666"));

        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("Country");

        cardExpDate.setForeground(new java.awt.Color(204, 204, 204));
        cardExpDate.setText("MM / YY");
        cardExpDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardExpDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardExpDateFocusLost(evt);
            }
        });
        cardExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardExpDateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setText("CARD");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logincat2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(115, 115, 115))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(cardExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cardCVC, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cardNumber)
                            .addComponent(cardEmail)
                            .addComponent(cardName)
                            .addComponent(countryList, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel5)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(cardEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardCVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(cardName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(countryList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logincat1.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberActionPerformed

    private void cardExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardExpDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardExpDateActionPerformed

    private void cardEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardEmailActionPerformed

    private void cardEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardEmailFocusGained
        if (cardEmail.getText().equals("")) {
            cardEmail.setForeground(Color.BLACK);
        }
        if (cardEmail.getText().equals("Ex: pethotel@abc.com")) {
            cardEmail.setText("");
            cardEmail.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_cardEmailFocusGained

    private void cardEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardEmailFocusLost
        if (cardEmail.getText().isEmpty()) {
            cardEmail.setText("Ex: pethotel@abc.com");
            cardEmail.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_cardEmailFocusLost

    private void cardNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNumberFocusGained
        if (cardNumber.getText().equals("1234 1234 1234 1234")) {
            cardNumber.setText("");
            cardNumber.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_cardNumberFocusGained

    private void cardNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNumberFocusLost
        if (cardNumber.getText().isEmpty()) {
            cardNumber.setText("1234 1234 1234 1234");
            cardNumber.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_cardNumberFocusLost

    private void cardExpDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardExpDateFocusGained
        if (cardExpDate.getText().equals("MM / YY")) {
            cardExpDate.setText("");
            cardExpDate.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_cardExpDateFocusGained

    private void cardExpDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardExpDateFocusLost
        if (cardExpDate.getText().isEmpty()) {
            cardExpDate.setText("MM / YY");
            cardExpDate.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_cardExpDateFocusLost

    private void cardCVCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardCVCFocusGained
        if (cardCVC.getText().equals("CVC")) {
            cardCVC.setText("");
            cardCVC.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_cardCVCFocusGained

    private void cardCVCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardCVCFocusLost
        if (cardCVC.getText().isEmpty()) {
            cardCVC.setText("CVC");
            cardCVC.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_cardCVCFocusLost

    private void cardNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNameFocusGained
        if (cardName.getText().equals("Ex: NGUYEN VAN AN")) {
            cardName.setText("");
            cardName.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_cardNameFocusGained

    private void cardNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNameFocusLost
        if (cardName.getText().isEmpty()) {
            cardName.setText("Ex: NGUYEN VAN AN");
            cardName.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_cardNameFocusLost

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        StripePaymentLogic payment = new StripePaymentLogic();
        String description = payment.StripePaymentLogic(cardName.getText(), amount);
        if(description =="error"){
            JOptionPane.showMessageDialog(this, "Error payment !");
        }else{
            Bill bill = new Bill(0, Integer.parseInt(id_customer), cardName.getText(), cardEmail.getText(), description);
            Payment paymentcustomer = new Payment();
            paymentcustomer.PaymentCustomer(bill);
            JOptionPane.showMessageDialog(this, "Successfully payment !");
            Customerapp customerapp = new Customerapp();
            customerapp.deleteCustomer(id_customer);
            this.dispose();
        }    
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardCVC;
    private javax.swing.JTextField cardEmail;
    private javax.swing.JTextField cardExpDate;
    private javax.swing.JTextField cardName;
    private javax.swing.JTextField cardNumber;
    private javax.swing.JComboBox<String> countryList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
