/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application;
import javax.swing.*; 
import java.awt.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eternal
 */
public class Sample2 extends javax.swing.JFrame {

    /**
     * Creates new form Sample2
     */
    
    //165, 750
    public Sample2() {
        initComponents();
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        customerTable.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Ma KH");
        defaultTableModel.addColumn("Ten KH");
        defaultTableModel.addColumn("SDT");
        defaultTableModel.addColumn("Dia chi");
        defaultTableModel.addColumn("CCCD");
    }
    
    int width = 170;
    int height = 750;
    
    void closeMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i=width; i>0; i--) {
                    slideMenu.setSize(i, height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        }).start();
    }
    
    void openMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i=0; i<width; i++) {
                    slideMenu.setSize(i, height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        mainBoard = new javax.swing.JPanel();
        slideMenu = new javax.swing.JPanel();
        slideOff = new javax.swing.JLabel();
        petHotelLogo = new javax.swing.JLabel();
        petHotelTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        home = new javax.swing.JLabel();
        customer = new javax.swing.JLabel();
        employee = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        helpOption = new javax.swing.JLabel();
        aboutUsInfo = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();
        slideOn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        homeInfo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        customerInfo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        employeeInfo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        petInfo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        mainBoard.setBackground(new java.awt.Color(255, 255, 255));
        mainBoard.setMaximumSize(new java.awt.Dimension(950, 750));
        mainBoard.setMinimumSize(new java.awt.Dimension(950, 750));
        mainBoard.setPreferredSize(new java.awt.Dimension(950, 750));

        slideMenu.setBackground(new java.awt.Color(255, 255, 255));
        slideMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        slideMenu.setMaximumSize(new java.awt.Dimension(170, 750));
        slideMenu.setMinimumSize(new java.awt.Dimension(170, 750));
        slideMenu.setPreferredSize(new java.awt.Dimension(170, 750));
        slideMenu.setRequestFocusEnabled(false);
        slideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slideOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Application/Turn off.png"))); // NOI18N
        slideOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slideOffMouseClicked(evt);
            }
        });
        slideMenu.add(slideOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 30, 30));

        petHotelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Application/images.jpg"))); // NOI18N
        slideMenu.add(petHotelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 33, -1, -1));

        petHotelTitle.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        petHotelTitle.setText("Pet Hotel");
        slideMenu.add(petHotelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 189, -1, -1));
        slideMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 236, 165, 10));

        home.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("Home");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        slideMenu.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 40));

        customer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customer.setText("Customer");
        customer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        customer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerMouseClicked(evt);
            }
        });
        slideMenu.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 170, 40));

        employee.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        employee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employee.setText("Employee");
        employee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employee.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeMouseClicked(evt);
            }
        });
        slideMenu.add(employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 170, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pets");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        slideMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 170, 40));
        slideMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 549, 165, 10));

        helpOption.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        helpOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpOption.setText("Help");
        slideMenu.add(helpOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 562, 170, 40));

        aboutUsInfo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        aboutUsInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutUsInfo.setText("About us");
        slideMenu.add(aboutUsInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 602, 170, 40));

        logOut.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        logOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOut.setText("Log out");
        slideMenu.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 642, 170, 40));

        slideOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Application/Open Menu.png"))); // NOI18N
        slideOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slideOnMouseClicked(evt);
            }
        });

        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Trang chủ");

        javax.swing.GroupLayout homeInfoLayout = new javax.swing.GroupLayout(homeInfo);
        homeInfo.setLayout(homeInfoLayout);
        homeInfoLayout.setHorizontalGroup(
            homeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeInfoLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabel5)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        homeInfoLayout.setVerticalGroup(
            homeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(728, Short.MAX_VALUE))
        );

        jPanel2.add(homeInfo, "card3");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Thông tin khách hàng");

        jScrollPane2.setViewportView(customerTable);

        javax.swing.GroupLayout customerInfoLayout = new javax.swing.GroupLayout(customerInfo);
        customerInfo.setLayout(customerInfoLayout);
        customerInfoLayout.setHorizontalGroup(
            customerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoLayout.createSequentialGroup()
                .addGroup(customerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerInfoLayout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabel9))
                    .addGroup(customerInfoLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        customerInfoLayout.setVerticalGroup(
            customerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jPanel2.add(customerInfo, "card2");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Thông tin nhân viên");

        javax.swing.GroupLayout employeeInfoLayout = new javax.swing.GroupLayout(employeeInfo);
        employeeInfo.setLayout(employeeInfoLayout);
        employeeInfoLayout.setHorizontalGroup(
            employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeInfoLayout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel6)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        employeeInfoLayout.setVerticalGroup(
            employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(728, Short.MAX_VALUE))
        );

        jPanel2.add(employeeInfo, "card4");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Thông tin thú cưng");

        javax.swing.GroupLayout petInfoLayout = new javax.swing.GroupLayout(petInfo);
        petInfo.setLayout(petInfoLayout);
        petInfoLayout.setHorizontalGroup(
            petInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petInfoLayout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel4)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        petInfoLayout.setVerticalGroup(
            petInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(728, Short.MAX_VALUE))
        );

        jPanel2.add(petInfo, "card5");

        javax.swing.GroupLayout mainBoardLayout = new javax.swing.GroupLayout(mainBoard);
        mainBoard.setLayout(mainBoardLayout);
        mainBoardLayout.setHorizontalGroup(
            mainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBoardLayout.createSequentialGroup()
                .addComponent(slideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainBoardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(slideOn)
                        .addContainerGap())))
        );
        mainBoardLayout.setVerticalGroup(
            mainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBoardLayout.createSequentialGroup()
                .addGroup(mainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainBoardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(slideOn)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(slideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slideOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideOffMouseClicked
        closeMenu();
    }//GEN-LAST:event_slideOffMouseClicked

    private void slideOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideOnMouseClicked
        openMenu();
    }//GEN-LAST:event_slideOnMouseClicked

    private void customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMouseClicked
        customerInfo.setVisible(true);
        homeInfo.setVisible(false);
        employeeInfo.setVisible(false);
        petInfo.setVisible(false);
    }//GEN-LAST:event_customerMouseClicked

    private void employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseClicked
        customerInfo.setVisible(false);
        employeeInfo.setVisible(true);
        homeInfo.setVisible(false);
        petInfo.setVisible(false);
    }//GEN-LAST:event_employeeMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        customerInfo.setVisible(false);
        employeeInfo.setVisible(false);
        homeInfo.setVisible(true);
        petInfo.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        petInfo.setVisible(true);
        customerInfo.setVisible(false);
        employeeInfo.setVisible(false);
        homeInfo.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sample2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sample2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sample2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sample2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sample2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutUsInfo;
    private javax.swing.JLabel customer;
    private javax.swing.JPanel customerInfo;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel employee;
    private javax.swing.JPanel employeeInfo;
    private javax.swing.JLabel helpOption;
    private javax.swing.JLabel home;
    private javax.swing.JPanel homeInfo;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logOut;
    private javax.swing.JPanel mainBoard;
    private javax.swing.JLabel petHotelLogo;
    private javax.swing.JLabel petHotelTitle;
    private javax.swing.JPanel petInfo;
    private javax.swing.JPanel slideMenu;
    private javax.swing.JLabel slideOff;
    private javax.swing.JLabel slideOn;
    // End of variables declaration//GEN-END:variables
}
